### ISSUE TITLE
Incorrect results of the unit tests

### ISSUE THREAD

**Issue by asia-makai** [PatrickTrentin88/omt_python_examples#3]
For a research project at our university, we'd like to use the OptiMathSAT library. We've come across this repo. It looks very useful. However, we're still struggling with the unit-tests. Could you please advise or redirect me to someone who may be able to help? 

My setup: 

- Ubuntu 20.04
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 
- optimathsat-1.7.3-linux-64-bit

I have no problems executing the tests, however, they don't return the expected results.
I've provided two examples below. If you have an idea of the direction  for us, it would be very helpful.

Thank you in advance.

E.g., 
```
ubuntu@saideh-2-clone:~/tmp/omt_python_examples-master$ ./unit-tests/minmax.py 
unknown
(objectives
(minmax unknown)
)
ubuntu@saideh-2-clone:~/tmp/omt_python_examples-master$ tail unit-tests/minmax.py 
            solve(env)
            get_objectives_pretty(env)

#
## EXPECTED OUTPUT
#
# sat
# (objectives
#   (minmax 16)
# )
```

And another one:
```
ubuntu@saideh-2-clone:~/tmp/omt_python_examples-master$ ./unit-tests/simple_omt.py 
sat
B1 : `true`
x1 : 9
x2 : 10
cost : 19
sat
B1 : `true`
x1 : 0
x2 : 1
cost : 1
sat
B1 : `true`
x1 : 7
x2 : 10
cost : 17
maxmin : 7
ubuntu@saideh-2-clone:~/tmp/omt_python_examples-master$ tail unit-tests/simple_omt.py 
#   B1 : `true`
#   x1 : 0
#   x2 : 1
#   cost : 1
# sat
#   B1 : `true`
#   x1 : 7
#   x2 : 8
#   cost : 15
#   minmax : 7

```

**Comment by PatrickTrentin88** [comment]
Thanks for the bug report!

One of the tests was missing a flag that became required over time. The other test had the wrong solution in the comments.
